name: /home/mdclarke/Drive/UASG_2025/env_UASG
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.15.3=hb03c661_0
  - arpack=3.9.1=nompi_hf03ea27_102
  - bcftools=1.22=h3a4d415_1
  - beagle=5.5_27Feb25.75f=hdfd78af_0
  - binutils_impl_linux-64=2.45=default_hfdba357_105
  - bioconductor-limma=3.28.10=0
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - curl=8.18.0=h4e3cde8_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gcc_impl_linux-64=15.2.0=hc5723f1_16
  - gfortran_impl_linux-64=15.2.0=h281d09f_16
  - giflib=5.2.2=hd590300_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=hda75c37_16
  - harfbuzz=12.2.0=h15599e2_0
  - htslib=1.22.1=h566b1c6_0
  - icu=75.1=he02047a_0
  - igraph=1.0.1=hfe3e89f_0
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-devel_linux-64=15.2.0=hcc6f6b0_116
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.86.3=h6548e54_0
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.54=h421ea60_0
  - libsanitizer=15.2.0=h90f66d4_16
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-devel_linux-64=15.2.0=hd446a21_116
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openjdk=25.0.1=h5755bd7_0
  - openssl=3.6.0=h26f9b46_0
  - pandoc=3.8.3=ha770c72_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.47=haa7fec5_0
  - perl=5.32.1=7_hd590300_perl5
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - r=4.5=r45hd8ed1ab_1009
  - r-askpass=1.2.1=r45h54b55ab_1
  - r-assertthat=0.2.1=r45hc72bb7e_6
  - r-backports=1.5.0=r45h54b55ab_2
  - r-base=4.5.2=h835929b_3
  - r-base64enc=0.1_3=r45h54b55ab_1008
  - r-bigd=0.3.1=r45hc72bb7e_1
  - r-biocmanager=1.30.27=r45hc72bb7e_0
  - r-bit=4.6.0=r45h54b55ab_1
  - r-bit64=4.6.0_1=r45h54b55ab_1
  - r-bitops=1.0_9=r45h54b55ab_1
  - r-blob=1.3.0=r45hc72bb7e_0
  - r-boot=1.3_32=r45hc72bb7e_1
  - r-broom=1.0.11=r45hc72bb7e_0
  - r-bslib=0.9.0=r45hc72bb7e_1
  - r-cachem=1.1.0=r45h54b55ab_2
  - r-callr=3.7.6=r45hc72bb7e_2
  - r-cards=0.7.1=r45hc72bb7e_0
  - r-cardx=0.3.1=r45hc72bb7e_0
  - r-cellranger=1.1.0=r45hc72bb7e_1008
  - r-class=7.3_23=r45h54b55ab_1
  - r-cli=3.6.5=r45h3697838_1
  - r-clipr=0.8.0=r45hc72bb7e_4
  - r-cluster=2.1.8.1=r45heaba542_1
  - r-codetools=0.2_20=r45hc72bb7e_2
  - r-colorspace=2.1_2=r45h54b55ab_0
  - r-commonmark=2.0.0=r45h54b55ab_1
  - r-conflicted=1.2.0=r45h785f33e_3
  - r-cpp11=0.5.3=r45h785f33e_0
  - r-crayon=1.5.3=r45hc72bb7e_2
  - r-crul=1.6.0=r45hc72bb7e_1
  - r-curl=7.0.0=r45h10955f1_1
  - r-data.table=1.17.8=r45h1c8cec4_1
  - r-dbi=1.2.3=r45hc72bb7e_2
  - r-dbplyr=2.5.1=r45hc72bb7e_1
  - r-digest=0.6.39=r45h3697838_0
  - r-dplyr=1.1.4=r45h3697838_2
  - r-dtplyr=1.3.2=r45hc72bb7e_1
  - r-ellipsis=0.3.2=r45h54b55ab_4
  - r-evaluate=1.0.5=r45hc72bb7e_1
  - r-fansi=1.0.7=r45h54b55ab_0
  - r-farver=2.1.2=r45h3697838_2
  - r-fastmap=1.2.0=r45h3697838_2
  - r-fontawesome=0.5.3=r45hc72bb7e_1
  - r-fontbitstreamvera=0.1.1=r45hc72bb7e_1007
  - r-fontliberation=0.1.0=r45hc72bb7e_1007
  - r-fontquiver=0.2.1=r45hc72bb7e_1007
  - r-forcats=1.0.1=r45hc72bb7e_0
  - r-foreign=0.8_90=r45h54b55ab_1
  - r-fs=1.6.6=r45h3697838_1
  - r-gargle=1.6.0=r45h785f33e_1
  - r-gdtools=0.4.4=r45ha0c56d8_0
  - r-generics=0.1.4=r45hc72bb7e_1
  - r-gfonts=0.2.0=r45hc72bb7e_3
  - r-ggfun=0.2.0=r45hc72bb7e_1
  - r-ggiraph=0.9.3=r45h8ff94db_0
  - r-ggplot2=4.0.1=r45h785f33e_0
  - r-ggrepel=0.9.6=r45h3697838_2
  - r-ggtangle=0.1.1=r45hc72bb7e_0
  - r-glue=1.8.0=r45h54b55ab_1
  - r-googledrive=2.1.2=r45hc72bb7e_1
  - r-googlesheets4=1.1.2=r45h785f33e_1
  - r-gt=1.2.0=r45hc72bb7e_0
  - r-gtable=0.3.6=r45hc72bb7e_1
  - r-gtsummary=2.5.0=r45hc72bb7e_0
  - r-haven=2.5.5=r45h6d565e7_1
  - r-here=1.0.2=r45hc72bb7e_0
  - r-highr=0.11=r45hc72bb7e_2
  - r-hms=1.1.4=r45hc72bb7e_0
  - r-htmltools=0.5.9=r45h3697838_0
  - r-htmlwidgets=1.6.4=r45h785f33e_4
  - r-httpcode=0.3.0=r45ha770c72_5
  - r-httpgd=2.0.4=r45h3697838_1
  - r-httpuv=1.6.16=r45h6d565e7_1
  - r-httr=1.4.7=r45hc72bb7e_2
  - r-ids=1.0.1=r45hc72bb7e_5
  - r-igraph=2.1.4=r45hf411e2a_2
  - r-isoband=0.3.0=r45h3697838_0
  - r-jquerylib=0.1.4=r45hc72bb7e_4
  - r-jsonlite=2.0.0=r45h54b55ab_1
  - r-juicyjuice=0.1.0=r45hc72bb7e_3
  - r-kernsmooth=2.23_26=r45ha0a88a1_1
  - r-knitr=1.51=r45hc72bb7e_0
  - r-labeling=0.4.3=r45hc72bb7e_2
  - r-later=1.4.5=r45h3697838_0
  - r-lattice=0.22_7=r45h54b55ab_1
  - r-lifecycle=1.0.5=r45hc72bb7e_0
  - r-litedown=0.9=r45hc72bb7e_0
  - r-lubridate=1.9.4=r45h54b55ab_1
  - r-magrittr=2.0.4=r45h54b55ab_0
  - r-markdown=2.0=r45hc72bb7e_1
  - r-mass=7.3_65=r45h54b55ab_0
  - r-matrix=1.7_4=r45h0e4624f_1
  - r-memoise=2.0.1=r45hc72bb7e_4
  - r-mgcv=1.9_4=r45h0e4624f_0
  - r-mime=0.13=r45h54b55ab_1
  - r-modelr=0.1.11=r45hc72bb7e_3
  - r-munsell=0.5.1=r45hc72bb7e_2
  - r-nlme=3.1_168=r45heaba542_1
  - r-nnet=7.3_20=r45h54b55ab_1
  - r-openssl=2.3.4=r45h50f7d53_0
  - r-otel=0.2.0=r45hc72bb7e_1
  - r-pillar=1.11.1=r45hc72bb7e_0
  - r-pkgconfig=2.0.3=r45hc72bb7e_5
  - r-prettyunits=1.2.0=r45hc72bb7e_2
  - r-processx=3.8.6=r45h54b55ab_1
  - r-progress=1.2.3=r45hc72bb7e_2
  - r-promises=1.5.0=r45hc72bb7e_1
  - r-ps=1.9.1=r45h54b55ab_1
  - r-purrr=1.2.1=r45h54b55ab_0
  - r-r6=2.6.1=r45hc72bb7e_1
  - r-ragg=1.5.0=r45h9f1dc4d_1
  - r-rappdirs=0.3.4=r45h54b55ab_0
  - r-rcolorbrewer=1.1_3=r45h785f33e_4
  - r-rcpp=1.1.1=r45h3697838_0
  - r-reactable=0.4.5=r45hc72bb7e_0
  - r-reactr=0.6.1=r45hc72bb7e_1
  - r-readr=2.1.6=r45h3697838_0
  - r-readxl=1.4.5=r45h10e25cc_1
  - r-recommended=4.5=r45hd8ed1ab_1008
  - r-rematch=2.0.0=r45hc72bb7e_2
  - r-rematch2=2.1.2=r45hc72bb7e_5
  - r-reprex=2.1.1=r45hc72bb7e_2
  - r-rlang=1.1.7=r45h3697838_0
  - r-rmarkdown=2.30=r45hc72bb7e_0
  - r-rpart=4.1.24=r45h54b55ab_1
  - r-rprojroot=2.1.1=r45hc72bb7e_1
  - r-rstudioapi=0.18.0=r45hc72bb7e_0
  - r-rvest=1.0.5=r45hc72bb7e_1
  - r-s7=0.2.1=r45h54b55ab_0
  - r-sass=0.4.10=r45h3697838_1
  - r-scales=1.4.0=r45hc72bb7e_1
  - r-selectr=0.5_1=r45hc72bb7e_0
  - r-shiny=1.12.1=r45h785f33e_0
  - r-sourcetools=0.1.7_1=r45h3697838_3
  - r-spatial=7.3_18=r45h54b55ab_1
  - r-stringi=1.8.7=r45h2dae267_1
  - r-stringr=1.6.0=r45h785f33e_0
  - r-survival=3.8_6=r45h54b55ab_0
  - r-sys=3.4.3=r45h54b55ab_1
  - r-systemfonts=1.3.1=r45h74f4acd_0
  - r-textshaping=1.0.4=r45h74f4acd_0
  - r-tibble=3.3.1=r45h54b55ab_0
  - r-tidyr=1.3.2=r45h3697838_0
  - r-tidyselect=1.2.1=r45hc72bb7e_2
  - r-tidyverse=2.0.0=r45h785f33e_3
  - r-timechange=0.3.0=r45h3697838_2
  - r-tinytex=0.58=r45hc72bb7e_0
  - r-triebeard=0.4.1=r45h3697838_4
  - r-tzdb=0.5.0=r45h3697838_2
  - r-unigd=0.1.2=r45h74010f2_3
  - r-urltools=1.7.3.1=r45h3697838_1
  - r-utf8=1.2.6=r45h54b55ab_1
  - r-uuid=1.2_1=r45h54b55ab_1
  - r-v8=8.0.1=r45h3697838_0
  - r-vctrs=0.6.5=r45h3697838_2
  - r-viridislite=0.4.2=r45hc72bb7e_3
  - r-vroom=1.6.7=r45h3697838_0
  - r-withr=3.0.2=r45hc72bb7e_1
  - r-xfun=0.56=r45h3697838_0
  - r-xml2=1.5.2=r45he78afff_0
  - r-xtable=1.8_4=r45hc72bb7e_7
  - r-yaml=2.3.12=r45h54b55ab_0
  - r-yulab.utils=0.2.3=r45hc72bb7e_0
  - readline=8.3=h853b02a_0
  - sed=4.9=h6688a6e_0
  - sysroot_linux-64=2.39=hc4b9eeb_5
  - tabix=1.11=hdfd78af_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tktable=2.10=h8d826fa_7
  - tzdata=2025c=hc9c84f9_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/mdclarke/Drive/UASG_2025/env_UASG
